### ISSUE TITLE
Wireman's E2 is garbled after the .txt workaround

### ISSUE THREAD

**Issue by emspike** [wiremod/wire#644]
After wireman is unpacked from the default_data_thingy, newlines and quotes are messed up. Using the wireman.txt straight from the repo works fine.

The file default_data_thingy unpacks: https://dl.dropboxusercontent.com/u/12612176/wireman/wireman_garbled.txt
The way it is in the repo: https://dl.dropboxusercontent.com/u/12612176/wireman/wireman_repo.txt

The view in E2: https://dl.dropboxusercontent.com/u/12612176/pics/wireman_noooo.png

I can't even gmod without wireman...

**Comment by AbigailBuccaneer** [comment]
I'll look into this this evening and make a GMod bug report if it's still broken.

**Comment by thegrb93** [comment]
Pretty sure this was fixed. If not, just build a new one.

**Comment by CaptainPRICE** [comment]
It is still not fixed.
#1154 < It were closed (for no reason).

(Yes, it can be fixed manually.)

**Comment by thegrb93** [comment]
Ok thanks for letting me know. I'll review that one later today.
